### ISSUE TITLE
NSFW providers

### ISSUE THREAD

**Issue by ghost** [phisher98/CXXX#11]
There used to be a repo that had 
https://www.pxxbay.com/
https://tube.perverzija.com/
https://eporner.com/
https://www.porntrex.com/
And they worked amazing with high quality videos, do you happen to know what happened to this repo or if these can be added to yours?

**Comment by phisher98** [comment]
2nd and 3rd are Added and 1st may not add as most of its sources doesn't look like it works and 4th may take time
