### ISSUE TITLE
StreamPlay Crash With LOGS

### ISSUE THREAD

**Issue by rebibeMee** [phisher98/CXXX#24]
Try to watch  "The Frog" then a minute then add subtitle to multiapi source it will crash.
![Screenshot_2024-09-14-14-37-58-941_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/1a879e2a-51f1-4065-8bfc-a8c88cdc132d)
![Screenshot_2024-09-14-14-38-20-362_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/4ef270cd-5548-4330-82c8-9612f9b59a3a)
![Screenshot_2024-09-14-14-38-31-395_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/e6ef8b48-b231-435f-b740-4ef347af6483)
![Screenshot_2024-09-14-14-38-36-115_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/2527fb30-6c66-4e37-8ddf-c204b0bf30fe)

**Comment by phisher98** [comment]
Its not a Extension issue and wrong Repo contact support in discord
